{"name": "Validate walking distance on google maps", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\afaheem\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\afaheem\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\googleMapSearchdef.py\", line 45, in step_impl\n    driver.waitOnElement(carFirstResultHours)\n  File \"C:\\test\\maps-cucumber-python-cross-browser\\utilities\\driverUtil.py\", line 54, in waitOnElement\n    return WebDriverWait(self.driver, 20).until(ec.visibility_of_element_located((By.XPATH, elemXpath)))\n  File \"c:\\users\\afaheem\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I go to Google Maps", "status": "passed", "start": 1586126396938, "stop": 1586126400510}, {"name": "When I input source and destination in maps", "status": "passed", "start": 1586126400511, "stop": 1586126401869}, {"name": "Then I verify walking distance in the maps", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\afaheem\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\afaheem\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\googleMapSearchdef.py\", line 45, in step_impl\n    driver.waitOnElement(carFirstResultHours)\n  File \"C:\\test\\maps-cucumber-python-cross-browser\\utilities\\driverUtil.py\", line 54, in waitOnElement\n    return WebDriverWait(self.driver, 20).until(ec.visibility_of_element_located((By.XPATH, elemXpath)))\n  File \"c:\\users\\afaheem\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1586126401871, "stop": 1586126421987}], "start": 1586126396918, "stop": 1586126422082, "uuid": "d7a06bb4-6cd0-4383-a815-4aca7bebd016", "historyId": "3ab13c2e0a9ace49eb75d308e60af3bf", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "asad"}, {"name": "tag", "value": "google-maps-walk"}, {"name": "feature", "value": "Google Map"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}